TheWall/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .root_view import api_root
from server.wallauth.views import obtain_auth_token

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api/get_auth_token/', obtain_auth_token, name='get_auth_token'),
    url(r'^api/user/', include('server.wallauth.urls', namespace="user")),
    url(r'^api/message/', include('server.wall_messages.urls', namespace='message')),
    url(r'^api/comment/', include('server.comments.urls', namespace='comment')),
    url(r'^', api_root),
]

server/wallauth/urls.py
from django.conf.urls import url
from rest_framework.urlpatterns import format_suffix_patterns
from . import views

urlpatterns = [
    url(r'^$', views.UserList.as_view(), name='walluser-list'),
    url(r'^(?P<pk>[0-9]+)/$', views.UserDetail.as_view(), name='walluser-detail'),
]

urlpatterns = format_suffix_patterns(urlpatterns)

server/comments/models.py
from django.db import models
from ..wall_messages.models import Message
from ..wallauth.models import WallUser

class Comment(models.Model):
    content = models.TextField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    creator = models.ForeignKey(WallUser, related_name="comments")
    message = models.ForeignKey(Message, related_name="comments")

server/wallauth/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.utils import timezone
from django.utils.http import urlquote
from django.utils.translation import ugettext_lazy as _
from django.core.mail import send_mail
from datetime import datetime
from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver
from rest_framework.authtoken.models import Token


class WallUserManager(BaseUserManager):
    def _create_user(self, email, password, is_staff, is_superuser, **extra_fields):
        """
        Creates and saves a User with the given email and password.
        """
        print (extra_fields, "are extra fields")
        now = timezone.now()
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email,
                          is_staff=is_staff, is_active=True,
                          is_superuser=is_superuser, last_login=now,
                          created_at=now, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        return self._create_user(email, password, False, False,
                                 **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        return self._create_user(email, password, True, True,
                                 **extra_fields)

class WallUser(AbstractBaseUser, PermissionsMixin):
    first_name = models.CharField(_('First Name'), max_length=100, blank=True)
    last_name = models.CharField(_('Last Name'), max_length=100, blank=True)
    email = models.EmailField(unique=True)
    created_at = models.DateTimeField(_('Created At'), auto_now_add=True)
    updated_at = models.DateTimeField(_('Updated At'), auto_now=True)
    is_staff = models.BooleanField(_('staff status'), default=False,
        help_text=_('Designates whether the user can log into this admin '
                        'site.'))
    is_active = models.BooleanField(_('active'), default=True,
        help_text=_('Designates whether this user should be treated as '
                    'active. Unselect this instead of deleting accounts.'))
    objects = WallUserManager()

    USERNAME_FIELD = 'email'
    EMAIL_FIELD = 'email'

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')
    
    def confirm(self):
        return None

    def get_full_name(self):
        """
        Returns the first_name plus the last_name, with a space in between.
        """
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        "Returns the short name for the user."
        return self.first_name

    def email_user(self, subject, message, from_email=None):
        """
        Sends an email to this User.
        """
        send_mail(subject, message, from_email, [self.email])

    def has_perm(self, perm, obj=None):
        return self.is_superuser

    def has_module_perms(self, app_label):
        return self.is_superuser

    def __unicode__(self):
        return self.email

@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_auth_token(sender, instance=None, created=False, **kwargs):
    if created:
        print("user created... creating token")
        Token.objects.create(user=instance)

server/wallauth/forms.py
from django.forms import ModelForm, ValidationError
from django.core import validators
from django import forms
from .models import WallUser
from datetime import datetime
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.utils.translation import ugettext_lazy as _

# CUSTOM DATE INPUT
class DateInput(forms.DateInput):
    input_type = 'date'

class NameField(forms.CharField):
    MIN_LENGTH = 3
    NAME_REGEX = r'^[a-zA-Z]+$'
    NameMinLengthValidator = validators.MinLengthValidator(
        MIN_LENGTH,
        "Name Fields must be %(limit_value)d or more characters long, you have %(show_value)d"
    )
    NameRegexValidator = validators.RegexValidator(
        NAME_REGEX,
        "Names must only contain letter characters"
    )
    def __init__(self, *args, **kwargs):
        super(NameField, self).__init__(*args, **kwargs)
        self.validators.append(NameField.NameMinLengthValidator)
        self.validators.append(NameField.NameRegexValidator)


class UpdateUser(forms.ModelForm):
    def __init__(self, *args, **kargs):
        super(UpdateUser, self).__init__(*args, **kargs)

    first_name = NameField()
    last_name = NameField()

    class Meta:
        model = WallUser
        fields = (
            'first_name',
            'last_name',
            'email',
        )

class RegistrationForm(UserCreationForm):

    def __init__(self, *args, **kargs):
        super(RegistrationForm, self).__init__(*args, **kargs)

    first_name = NameField()
    last_name = NameField()

    password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={
            'class': 'form-control'
        }),
        label="Password"
    )
    password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={
            'class': 'form-control'
        }),
        label="Confirm Password"
    )

    class Meta:
        model = WallUser
        fields = [
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2'
        ]

server/wallauth/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from .models import WallUser
from rest_framework import parsers, renderers
from rest_framework.permissions import IsAuthenticated, AllowAny
from rest_framework.authtoken.models import Token
from rest_framework.response import Response
from rest_framework.views import APIView
from .serializers import UserSerializer, MyAuthTokenSerializer
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework import generics, mixins, status

class UserList(mixins.ListModelMixin,
               mixins.CreateModelMixin,
               generics.GenericAPIView):
    queryset = WallUser.objects.all()
    serializer_class = UserSerializer
    permission_classes = (AllowAny,)

    def get(self, request, *args, **kwargs):
        return self.list(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        _status = status.HTTP_200_OK
        serialized = self.serializer_class(data=request.data)

        if serialized.is_valid():
            token = serialized.save()
            return Response({"token":token.key}, status=_status)
        else:
            _status = status.HTTP_400_BAD_REQUEST
            return Response(serialized.errors, status=_status)

        #self.create(request, *args, **kwargs)

class UserDetail(mixins.RetrieveModelMixin,
                 mixins.UpdateModelMixin,
                 mixins.DestroyModelMixin,
                 generics.GenericAPIView):
    queryset = WallUser.objects.all()
    serializer_class = UserSerializer

    def get(self, request, *args, **kwargs):
        return self.retrieve(request, *args, **kwargs)

    def put(self, request, *args, **kwargs):
        return self.update(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
        return self.destroy(request, *args, **kwargs)

class MyObtainAuthToken(APIView):
    throttle_classes = ()
    permission_classes = ()
    parser_classes = (parsers.FormParser, parsers.MultiPartParser, parsers.JSONParser,)
    renderer_classes = (renderers.JSONRenderer,)
    serializer_class = MyAuthTokenSerializer

    def post(self, request, *args, **kwargs):
        serializer = self.serializer_class(data=request.data,
                                           context={'request': request})
        serializer.is_valid(raise_exception=True)
        user = serializer.validated_data['user']
        token, created = Token.objects.get_or_create(user=user)
        return Response({'token': token.key})


obtain_auth_token = MyObtainAuthToken.as_view()

server/wallauth/templates/loginreg/changepw.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title></title>
    </head>
    <body>
        <h1>Change ur pw??</h1>
        <form class="" action="pw_change" method="post"> {% csrf_token %}
            {{ form }}
            <input type="submit" name="" value="send">
        </form>
    </body>
</html>

server/wallauth/templates/loginreg/index.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset='UTF-8'>
		<title>The Wall</title>
		{% load staticfiles %}
		<link rel="stylesheet" href="{% static '/css/main.css' %}" media="screen">
		<link rel="stylesheet" href="{% static '/loginreg/css/loginreg.css' %}" media="screen">
	</head>
	<body>
		{% include "templates/nav.html" %}
		<div class="form-block">
			<h2>Register.</h2>
			<form class="" action="/try/1" method="post">{% csrf_token %}
				{% for field in reg_form %}
				{% if field.errors %}
				{% for error in  field.errors %}
				<p class="form-error">{{ error }}</p>
				{% endfor %}
				<div class="control-group error">
					{{ field.label_tag }}
					{{ field }}
					<div class="controls">
					</div>
				</div>
				{% else %}
				<div class="form-group">
					{{ field.label_tag }}
					{{ field }}
				</div>
				{% endif %}
				{% endfor %}
				<input type="submit" name="" value="Register">
			</form>
		</div>
		<div class="form-block">
			<h2>Login.</h2>
			<form class="" action="/try/2" method="post">{% csrf_token %}
				{% if log_form.errors %}
					{% for error in log_form.non_field_errors %}
						<p class="form-error">{{ error }}</p>
					{% endfor %}
				{% endif %}
				{% for field in log_form %}
				<div class="form-group">
					{{ field.label_tag }}
					{{ field }}
				</div>
				{% endfor %}
				<input type="submit" name="" value="Login">
			</form>
			<p>Forgot your password?</p>
			<a href="/pw_change">Reset</a>
		</div>
	</body>
</html>

server/wallauth/templates/loginreg/walluser_detail.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title></title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% load staticfiles %}
		<link rel="stylesheet" href="{% static '/css/main.css' %}" media="screen">
		<link rel="stylesheet" href="{% static '/loginreg/css/loginreg.css' %}" media="screen">
        
    </head>
    <body>
        {% include "templates/nav.html" %}
        <h1>{{ object.first_name }} {{ object.last_name }}</h1>
        <hr>
        <ul>
            <li>Email: {{ object.email }}</li>
            <li>Joined: {{ object.created_at }}</li>
            <li>Last Login: {{ object.last_login }}</li>
            <li>Posted: {{ object.post_set.count }} times</li>
            <li>Commented: {{ object.comment_set.count }} times</li>
            <li>First Post: {{ first_post }}</li>
        </ul>
        {% if user.id == object.id %}
            <a href="{% url 'user:edit' object.id %}"><button type="">Edit Profile</button></a>
        {% endif %}
    </body>
</html>

server/wallauth/templates/loginreg/walluser_update.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title></title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% load staticfiles %}
		<link rel="stylesheet" href="{% static '/css/main.css' %}" media="screen">
		<link rel="stylesheet" href="{% static '/loginreg/css/loginreg.css' %}" media="screen">
        
    </head>
    <body>
        {% include "templates/nav.html" %}
       <form action="{% url 'user:edit' id %}" method="post">{% csrf_token %}
            {% for field in form %}
            {% if field.errors %}
				{% for error in  field.errors %}
				<p class="form-error">{{ error }}</p>
				{% endfor %}
            <div class="control-group error">
                {{ field.label_tag }}
                {{ field }}
                <div class="controls">
                </div>
            </div>
            {% else %}
            <div class="form-group">
                {{ field.label_tag }}
                {{ field }}
            </div>
            {% endif %}
            {% endfor %}
            <input type="submit" name="" value="Register">
        </form>
    </body>
</html>